### ISSUE TITLE
"Unable to mount storage" with encrypted partition

### ISSUE THREAD

**Issue by StephenKing** [TeamWin/android_device_bq_piccolo#1]
I have encrypted my system in CM13 (build from march) and decryption fails in TWRP (2.8 to 3.0.2) with error "Unable to mount storage". Thus, I cannot upgrade my CM.

I already tried the custom [test build](https://s.basketbuild.com/filedl/devs?dev=Kra1o5&dl=Kra1o5/bq/piccolo/Test/TWRP-piccolo_decryptt1.img) by @Kra1o5 from TeamWin/Team-Win-Recovery-Project#699, which however also does not help.

Here are my recovery logs from [stock 3.0.2-0](https://gist.github.com/StephenKing/975a09c5dd23152defcc529beedd6ffb) and [@Kra1o5's build](https://gist.github.com/StephenKing/975a09c5dd23152defcc529beedd6ffb#file-recovery-piccolo_decryptt1-log).

**Comment by Kra1o5** [comment]
Hi @StephenKing ,

Can you try to mount system and firmware partitions in twrp before try to decrypt?

Greetings

**Comment by StephenKing** [comment]
Hi @Kra1o5, thanks for your quick reply.
when I cancel the initial decryption dialogue and go to the _Mount_ menu, I can select _firmware_ and _System_ partitions, but can continue only using the _Decrypt Data_ button (where I enter the PIN, which again fails resp. hangs in the test build). Not sure, if I'm correctly following you.

**Comment by Kra1o5** [comment]
Yes, this is the correct process.

**Comment by Bondarz** [comment]
hey @Kra1o5  

what should i select if i want to flash the image?
"System Image" "Boot" or "Revovery"?

by the way: there is no "firmware" partition.

Thanks

![screenshot_1970-01-06-22-18-48](https://cloud.githubusercontent.com/assets/19914015/16178311/68e3326a-3644-11e6-8aae-7dd0209e5b74.png)
![screenshot_1970-01-06-22-18-12](https://cloud.githubusercontent.com/assets/19914015/16178310/68e2e210-3644-11e6-9dde-e2c881275dc2.png)
![screenshot_1970-01-06-22-18-03](https://cloud.githubusercontent.com/assets/19914015/16178312/68e35c22-3644-11e6-9eaa-41eb26285914.png)

**Comment by Bondarz** [comment]
any ideas @Kra1o5 ? ;)

**Comment by Kra1o5** [comment]
Hi @Bondarz ,

Sorry for the delay, Im busy atm.

I refer to this partitions in my test build in "Mount" .

Greetings

**Comment by Bondarz** [comment]
Ok, installed the image now via "boot" and "recovery"

first boot aber choosing "boot": entered my PIN, still wrong password
second boot after flash as "recovery": entered the PIN, than a loop for minutes, trying to decrypt after entering my PIN...

"data" still with 0mb inside twrp

now i can`t boot into my android, think "boot" was the wrong choice? ;)
flashed CM13 and the gapps again, this fixed my boot problem.

log (with your image): http://pastebin.com/0V1ngmd0
hm..befor the image it was at 3.0.2-1, after flashing the image its 3.0.2-0
old log: http://pastebin.com/Eig9DFp3

**Comment by Kra1o5** [comment]
Hi, thanks for logs! I will check asap (Probably weekend).

Greetings

**Comment by compiaffe** [comment]
@Kra1o5 and @StephenKing I experience the same issue on my BQ Aquaris M5 with both
twrp-3.0.2-1-piccolo.img
twrp-3.0.2-0-piccolo.img

**Comment by stucki** [comment]
@Kra1o5 Any update here?

**Comment by Kra1o5** [comment]
Hi @stucki ,

Im very busy atm but im checking it now.

Sorry for the delay!

Greetings

**Comment by Kra1o5** [comment]
Hi @stucki ,

I cant get it working, it stuck in eternal loop at decrypt page.

**Comment by Kra1o5** [comment]
Hi @stucki @compiaffe @StephenKing @Bondarz ,

Sorry for the big delay! 

I think is now fixed, someone to test it?

Here the image: https://s.basketbuild.com/filedl/devs?dev=Kra1o5&dl=Kra1o5/bq/piccolo/Test/TWRP-piccolo_decryptt2.img

Greetings

**Comment by StephenKing** [comment]
Thanks for the build, @Kra1o5. Unfortunately, it still fails to decrypt.

**Comment by Bondarz** [comment]
**Ok, looks like i can decrypt :)** @Kra1o5., thanks

**Before:**
twrp-3.0.2-1-piccolo.img
FirmwareMM_v4.1.0_signed.zip 
cm-13.0-20160725-UNOFFICIAL-piccolo.zip
gapps

**now:**  twrp-3.0.2-0 (piccolo_decryptt2.img) (why 2-0 instead of 2-1?)
installed the image as "recovery" inside from TWRP twrp-3.0.2-1 and restarded my phone.

backuped my whole phone after decrypt my m5-> works with my normal decpryt PIN.
the twrp interface is now german -> i think before it was english?

new log: http://pastebin.com/qVrj2n3t

**Comment by Kra1o5** [comment]
Hi @StephenKing ,

What is your configs?

@Bondarz Yeah dont worry about -0 or -1 because is device specific so are the same version.

**Comment by StephenKing** [comment]
@Kra1o5 not sure what config you mean. I've booted the image via `fastboot boot`, have a number-only PIN.

**Comment by Kra1o5** [comment]
@StephenKing Yeah I refer to method, PIN in that case.

You refer to fastboot flash recovery TWRP-piccolo_decryptt2.img ?

**Comment by StephenKing** [comment]
No, I booted it from the bootloader via USB and `fastboot boot TWRP-piccolo_decryptt2.img`. But I can just try to flash it to recovery. Gimme a sec..

**Comment by Kra1o5** [comment]
@StephenKing 

Is better flash the image to get it working proprerly.

**Comment by StephenKing** [comment]
Flashed on `recovery` partition does not work either.
[Here's](https://gist.github.com/StephenKing/975a09c5dd23152defcc529beedd6ffb#file-twrp-piccolo_decryptt2-img-txt) the content of `/cache/recovery/last_log`.

**Comment by Kra1o5** [comment]
@StephenKing  Seems like it not getting flashed, its show 3.0.2-1 not 3.0.2-0 .

**Comment by StephenKing** [comment]
Don't scroll to the very top. These are the logs I linked previously, I'm only grouping them in a Gist. See [here](https://gist.github.com/StephenKing/975a09c5dd23152defcc529beedd6ffb#file-twrp-piccolo_decryptt2-img-txt-L314).

**Comment by Kra1o5** [comment]
You try to update firmware to 4.1.0?

Here the zip: https://s.basketbuild.com/devs/eloimuns/bq/piccolo/

**Comment by StephenKing** [comment]
Umm.. what's that? How do I flash that?

**Comment by Kra1o5** [comment]
In theory you can flash it from twrp, because it not use data partition.

**Comment by StephenKing** [comment]
But.. that's the original Aquaris Android version? Or what's that? Can I flash that thing, if I can't decrypt my System partition (I mean.. I can't update CM because of that).

Is there maybe any way to _revert_ the encryption? Maybe updating and then encrypting again picks some different algorithm or so.

**Comment by Kra1o5** [comment]
One thing is OS and another firmware, this flash some partitons to update firmware not to update OS.

You cant flash CM because it use data for somethings.

Encryptation only do this on /data partition not /system or others.

**Comment by StephenKing** [comment]
![Yay](http://a.memegen.com/130e8o.gif)

That (installing the firmware ZIP from recovery) helped! I was now able to update to latest CM (had to flash TWRP once more as it somehow completely vanished).

Thanks a lot @Kra1o5 and @stucki!

**Comment by Kra1o5** [comment]
@StephenKing  Glad to hear that 😁

Greetings

**Comment by StephenKing** [comment]
How can I donate?

**Comment by Kra1o5** [comment]
@StephenKing thanks! but you dont need to ☺

**Comment by StephenKing** [comment]
Thank's. I'd be happy to do, if you send me a paypal address or so. You made me able to install updates on my phone again!

**Comment by Kra1o5** [comment]
@StephenKing  You can find it here: http://www.android-hilfe.de/thema/rom-6-0-cyanogenmod-13-0-fuer-das-bq-aquaris-m5-weekly.735689/

Regards

**Comment by StephenKing** [comment]
Thanks for your help and keep up that good work!

**Comment by stucki** [comment]
@Kra1o5 What did you change to make this work? The image that you published in https://github.com/TeamWin/android_device_bq_piccolo/issues/1#issuecomment-235677063 is newer than the latest image at https://dl.twrp.me/piccolo/. Can you somehow update it?

**Comment by Kra1o5** [comment]
@stucki Here the changes: https://github.com/TeamWin/android_device_bq_piccolo/commit/259bd41070f8becae1a28fa44d40ff1d3d5698e3

It will be fixed in next twrp release.

Greetings

**Comment by stucki** [comment]
Great, thanks!
